### ISSUE TITLE
Support superscripts/subscripts

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#12]
If a font has super/sub character alternates, BonMot should be able to use them. If it does not, BonMot should be able to report this in a run-time log message or exception.

Nice to have: if a font doesn't have proper super/sub alternates, some designers will still accomplish the effect using a heaver weight, smaller size, and baseline shift (all of which are currently supported in BonMot). Can we make this process more streamlined, perhaps with special API for creating super/sub attributes to use when real alternate characters are not available?

**Comment by KingOfBrian** [comment]
Dup #173
