### ISSUE TITLE
Support character alternates

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#13]
Some fonts have alternate glyphs for some characters. These include standard kinds like small caps and superscripts/subscripts, and also include stylistic alternates for different uses (e.g. different `®` for headline and body text). BonMot should have a way to query which of these is are available in a font, and to enable easy use of them if they are available. The querying part can be done using the C functions in Core Text.

**Comment by KingOfBrian** [comment]
Dup #173
