### ISSUE TITLE
Add chain-starting convenience methods for Swift

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#132]
Idea via @KingOfBrian [here](https://github.com/Raizlabs/BonMot/pull/131#issuecomment-204750980): 

For Swift only, add static getters that make it easier to kick off a chain without parentheses, like this:

```swift
extension BONChain {

    static string: BONChainString {
        return BONChain().string
    }

    static string: BONChainImage {
        return BONChain().image
    }

    // ... etc etc for all properties
}
```

This would let you start a chain with `BONChain.string("hello")` instead of `BONChain().string("hello")`.

**Comment by KingOfBrian** [comment]
Resolved in 4.0
