### ISSUE TITLE
UIKit Setup Problem via PodFile

### ISSUE THREAD

**Issue by yoshiboarder** [Raizlabs/BonMot#134]
I'm trying to set BonMot library..

Podfile is here

use_frameworks!
pod 'Parse'
pod 'ParseUI'
pod 'BonMot'
pod 'BonMot/UIKit'

after that I got an this message.

<img width="428" alt="2016-04-08 9 32 51" src="https://cloud.githubusercontent.com/assets/12643700/14401198/d0d3a0dc-fe43-11e5-98aa-22660575287e.png">

Could you helping me?

Thank you

**Comment by ZevEisenberg** [comment]
Sorry, I should have spotted this sooner, and it's totally my fault. I haven't released the UIKit utilities in a tag yet. The release is gated by my ability to get some tests working (see my open pull request). For now, if you want to use the UIKit utilities, you'll have to point the repository at the latest commit on the `master` branch. You can learn how here: https://guides.cocoapods.org/using/the-podfile.html

I'll try to get the 3.0 release out soon with the UIKit utilities and some other stuff I've been working on.

**Comment by yoshiboarder** [comment]
Ok~!

Thank you for kindly reply

I hope meet UIKit soon!

:)

**Comment by ZevEisenberg** [comment]
@yoshiboarder BonMot 3.0 has been released with support for the UIKit utilities. Try it out and let me know how it works out!

**Comment by ZevEisenberg** [comment]
@yoshiboarder thanks for responding. Closing this.
