### ISSUE TITLE
Make UIKit extensions less confusing

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#136]
Re: https://github.com/Raizlabs/BonMot/pull/131#discussion_r58295255

Setting the chain should always override what's currently in the label. Any other behavior is too magical. 

@KingOfBrian pointed this out. @Imperiopolis let me know if this would bum you out, but I think it makes the most sense as a general-purpose API.

**Comment by Imperiopolis** [comment]
Works for me.
