### ISSUE TITLE
Underlining

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#14]
Don't bother implementing this unless someone specifically requests it for a shipping product, and even then, try to talk them out of it. No one likes underlining except my high school English teachers.

**Comment by lifely** [comment]
Hello, i'm sure you're gonna talk me out of it but could I specifically request this ? :x
 
It's not that i like this or not, it's just that specs are specs and sometime you don't choose what you have to do.

Also as a wrapper around attributedStrings shouldn't BonMot handle all it can do ? Maybe if you don't explicitly implement it, having a way to add attributes to `BONChain` object would be appreciated.

**Comment by ZevEisenberg** [comment]
Definitely! Specs, as you so rightly point out, are specs :D

If you’d like to take a crack at a PR, I’d be happy to provide help if you need it. It should be pretty similar to the way font and color are implemented, if you need a stating point.

**Comment by ZevEisenberg** [comment]
Oh, and I agree that eventually BonMot should support everything that attributed strings do. Definitely a medium-term goal, after basic usability improvements and a better Swift interface.

**Comment by ZevEisenberg** [comment]
Going to do separate properties for underline style and underline color, in case you want to specify the style but stick with the default text color. The color part is easy, because it behaves just like the existing `color` and `backgroundColor` properties that BonMot already has.

`NSUnderlineStyle`, however, is weird:

```objc
// This defines currently supported values for NSUnderlineStyleAttributeName and NSStrikethroughStyleAttributeName. NSUnderlineStyle*, NSUnderlinePattern*, and NSUnderlineByWord are or'ed together to produce an underline style.
typedef NS_ENUM(NSInteger, NSUnderlineStyle) {
    NSUnderlineStyleNone                                    = 0x00,
    NSUnderlineStyleSingle                                  = 0x01,
    NSUnderlineStyleThick NS_ENUM_AVAILABLE(10_0, 7_0)      = 0x02,
    NSUnderlineStyleDouble NS_ENUM_AVAILABLE(10_0, 7_0)     = 0x09,

    NSUnderlinePatternSolid NS_ENUM_AVAILABLE(10_0, 7_0)      = 0x0000,
    NSUnderlinePatternDot NS_ENUM_AVAILABLE(10_0, 7_0)        = 0x0100,
    NSUnderlinePatternDash NS_ENUM_AVAILABLE(10_0, 7_0)       = 0x0200,
    NSUnderlinePatternDashDot NS_ENUM_AVAILABLE(10_0, 7_0)    = 0x0300,
    NSUnderlinePatternDashDotDot NS_ENUM_AVAILABLE(10_0, 7_0) = 0x0400,

    NSUnderlineByWord NS_ENUM_AVAILABLE(10_0, 7_0)            = 0x8000
} NS_ENUM_AVAILABLE(10_0, 6_0);
```

It's sort of a bitmask, but you can only combine one Style, one Pattern, and optionally ByWord. Wondering which I should do (on both `BONChain` and `BONText`):

1. Expose `.underlineStyle(NSUnderlineStyle style)`
 - :white_check_mark: pretty concise to call this with some `|`ed values, and the final code is pretty readable because `NSUnderlineStyle` is clearly worded.
 - :white_check_mark: more familiar to people who already know `NSUnderlineStyle` API, although :warning: that isn't really a design goal of BonMot.
 - :warning: Harder to query `BONText` for individual values, because you have to do bitwise operations unless we expose convenience getters.
1. Expose three separate properties, to abstract away the quasi-bitmask weirdness:
 - `.underlineStyle(BONUnderlineStyle style)`
 - `.underlinePattern(BONUnderlinePattern pattern)`
 - `.underlineByWord(BOOL byWord)`
 - :white_check_mark: easier to query a `BONText` for these properties separately.
 - :warning: poor autocomplete support in Xcode for the chain able block syntax. It doesn't tell you the type, so you might accidentally pass `NSUnderlineStyle` values and then get confusing results. Not sure if Swift improves this at all.
- :warning: wordier, but :white_check_mark: more explicit, to express underline styles.

Anyone have any thoughts? @lifely @ateliercw @KingOfBrian @jkaufman?

**Comment by ZevEisenberg** [comment]
One more caveat: all these values can also be used for `NSStrikethroughStyleAttributeName`, which I might as well add while I'm at it. If I got with option 1, that's just two extra properties (strikethrough style and strikethrough color). If I go with option 2, that's four extra properties (strikethrough color, strikethrough style, strikethrough pattern, and strikethrough byWord). But it's really just two sets of four properties that look and work the same, so it's not bad enough that I would consider it ground for not doing it that way.

**Comment by ZevEisenberg** [comment]
Just for clarity, here are best and worst cases of the two forms.

```objc
// 1. Best case
// everything else is default, and color is same as text color
BONChain.new.underlineStyle(NSUnderlineStyleSingle);

// 1. Worst case
BONChain.new
.underlineStyle(NSUnderlineStyleDouble
                | NSUnderlinePatternDash // Or however you want to wrap these.
                | NSUnderlineByWord)     // Could also make a local variable first.
.underlineColor([UIColor blueColor]);

// 2. Best case
// everything else is default, and color is same as text color
BONChain.new.underlineStyle(BONLineStyleSingle);

// 2. Worst case
BONChain.new
.underlineStyle(BONLineStyleDouble)
.underlineStyle(BONLinePatternDash)
.underlineByWord(YES)
.underlineColor([UIColor blueColor]);
```

**Comment by KingOfBrian** [comment]
I like sticking with system enumeration/options. The additional enumerations could provide some type safety to a few possible mis-configurations, but your API mapping would be fragile to API changes in the future, as well as being a new thing the developer would have to learn.

Also -- I'm guessing that the  2.Worst case should be `.underlinePattern(BONLinePatternDash)`

**Comment by lifely** [comment]
Hey, 

Well lets say you didn't really give me a lot of time to respond : ) but I did implement something.
As i said in the pull-request I agree with @KingOfBrian that sticking with the system enumeration is better and more natural for an accustomed developer of the community.

Finally i would like to think of a way to enable developer not to wait for such "missing feature", i'll probably make another issue if you agree, what do you think about the idea of having something like : 
`BONChain.new.attribute(NSUnderlineStyleAttributeName, @(NSUnderlineStyleSingle))`

Also, you made me giggle when you mentioned : 
> a better Swift interface.

**Comment by ZevEisenberg** [comment]
@lifely I agree that arbitrary attributes would probably be useful, although I don't want it to be a crutch that prevents adding new attributes like underlining.
