### ISSUE TITLE
Expose names of BONSpecial characters

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#146]
It would be nice to be able to easily access the names of the characters exposed in `BONSpecial`, including the enclosing curly braces. This would make it easy to include things like `{noBreakSpace}` in localized strings, and then replace them at run time, which is what I'm currently trying to do. I would want to be able to do something like `BONCharacter.NoBreakSpace.name` to get `{noBreakSpace}`.

**Comment by KingOfBrian** [comment]
The game plan is to add support to the 4.0 XMLStyleRule API and make the behavior easy to adopt in custom XMLStyler implementations. ie: `This is an<BON:noBreakSpace/>example`
