### ISSUE TITLE
Ability to replace special characters in localized strings

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#147]
I'd like to be able to format a localized string like `Sign{noBreakSpace}in`, and then have BonMot automatically replace the text in curly braces with a non-breaking space (U+00A0). For speed, have an option to pass into `BONChain` the characters that I expect to have to replace, or have API for doing a single character, so we don't have to loop through all of `BONSpecial` if we know we're only going to be looking for a non-breaking space. But also have a way to look for all strings for cases where thoroughness or code cleanliness trumps speed.

**Comment by KingOfBrian** [comment]
Duping to #146
