### ISSUE TITLE
Support NSLinkAttributeName

### ISSUE THREAD

**Issue by angelmixu** [Raizlabs/BonMot#150]
It would be cool if for example I have:

"You accept the **Terms Of Service**"

with 'Terms Of Service' clickable and calling some handler/action for opening links, segue, or doing something.

**Comment by ZevEisenberg** [comment]
I believe the link tapping would have to be handled by a `UITextView` or perhaps [TTTAttributedLabel](https://github.com/TTTAttributedLabel/TTTAttributedLabel). But BonMot could certainly support adding `NSLinkAttributeName` to a string. Would you be interested in adding a pull request to that effect, @angelmixu?

**Comment by angelmixu** [comment]
Yup, I was looking for an overpowered UILabel in Swift and just got to TTTAttributedLabel and BonMot, I liked a lot BonMot but lacked touch sections.
@ZevEisenberg right now I'm quite busy, but in some time I'll be glad to try to implement it :)

**Comment by ZevEisenberg** [comment]
I've renamed this issue, because I think adding `NSLinkAttributeName` is a great idea and I'd like it to be a part of BonMot. I'll try to get to it soon, but if someone else wants to add it, I'm happy to help if you get stuck.

**Comment by ZevEisenberg** [comment]
To clarify: I probably won't add link-tapping detection to BonMot. It should be easy to use BonMot to generate the link (once this issue is closed), and then pass the attributed string on to `TTTAttributedLabel` or `UITextView`.
