### ISSUE TITLE
Explicitly describe BonMot attributes that do not have a 1:1 mapping with NSAttributedString

### ISSUE THREAD

**Issue by jatraiz** [Raizlabs/BonMot#169]
I ran into this with 'tracking'. Being a newb to font things I didn't know that this meant 'letter spacing' or that it related to achieving letter spacing with so-called kerning in NSAttributed strings. 

so in the readme, at least have it say 'tracking (character spacing)'

**Comment by ZevEisenberg** [comment]
Also for consideration: `figureSpacing` and `figureStyle` and their enum values are technically correct, but the readme should have clarification of what those mean in non-typography-nerd-speak.

**Comment by KingOfBrian** [comment]
This will be handled by #103
