### ISSUE TITLE
Rename figureStyle and figureSpacing and their associated enums

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#170]
Those are the pedantic typographic terms, but it's much clearer to use "number spacing" and "number case", with enum values "proportional", "monospace", "uppercase", and "lowercase". The typography nerd in me cries a bit, but it's so much clearer to most users than the terms we have in there now. Probably not worth doing for Obj-C unless there is another major release, but a good idea for the potential future Swift rewrite.

**Comment by KingOfBrian** [comment]
Resolved in 4.0
