### ISSUE TITLE
Update Example App

### ISSUE THREAD

**Issue by KingOfBrian** [Raizlabs/BonMot#175]
Update the example App to show better.

- [x] Default to Style Page
- [x] Add sub-pages for Dynamic Type examples
- [x] Make existing pretty styles Dynamic Type
- [x] Make the whole app 1 tableview
- [x] Remove fake content size category simulation.
- [x] Move GNUPlot code to a unit test
- [x] Restore RZ Red
- [ ] Shorten Figure Style examples
- [x] Rename project to BonMot-Example
- [x] Rename target to BonMot-iOS

**Comment by ZevEisenberg** [comment]
RZ Red: 
```objc
[UIColor colorWithRed:0.927
                           green:0.352
                            blue:0.303
                           alpha:1.0];
```

**Comment by KingOfBrian** [comment]
What do you think of moving the figure style examples to the bottom of the list and checking this off the list? I think it's in pretty good shape.

**Comment by ZevEisenberg** [comment]
Works for me. We may end up putting the constraint examples down there as well.
