### ISSUE TITLE
Faster Tag Substitution

### ISSUE THREAD

**Issue by KingOfBrian** [Raizlabs/BonMot#177]
BonMot 4.0 uses `(NS)XMLParser`. We believe there are some performance gains to be made by using a home-grown XML parser that supports only the subset of features that we care about.

NOTE: We currently don't see a lot of value in maintaining the custom start/end tag approach. Argue your case here!

**Comment by ZevEisenberg** [comment]
`(NS)XMLParser` seems to be doing fine. Feel free to reopen if you see specific performance issues you'd like to see addressed.
