### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by KingOfBrian** [Raizlabs/BonMot#181]
Acceptance Criteria:
- [x] Get tests passing on buddybuild, or determine that buddybuild won't work for this project.
- [x] Run tests under Swift 2.3 and 3.0. Bonus points for Swift 2.2.
- [x] Run tests on:
 - [x] iOS 9.3
 - [x] iOS 10.0
 - [ ] macOS 10.11 or macOS 10.12

**Comment by ZevEisenberg** [comment]
This line is causing test failures on the iOS 9 simulator:

```swift
style.styleAttributes(traitCollection: UITraitCollection(preferredContentSizeCategory: contentSizeCategory))
```

@KingOfBrian can we just disable those tests, or stub that method, when running on iOS 9? Or perhaps add that method on iOS 9 via an extension?

**Comment by KingOfBrian** [comment]
Good catch!

**Comment by KingOfBrian** [comment]
Actually, can you point to a log? It's working on 4s 9.0 and 5s 9.0 for me, but I'm building with iOS 9.3

**Comment by ZevEisenberg** [comment]
Here's one: https://dashboard.buddybuild.com/apps/5723679e7b69200100ba4c35/build/57d317967483790100237dee#logs

**Comment by KingOfBrian** [comment]
Ahh, was running 2.2 on 9.0 which doesn't run these tests via a #if swift. Interestingly running on 2.3 / 9.0 gives me this error.

![screen shot 2016-09-13 at 11 02 58 am](https://cloud.githubusercontent.com/assets/114322/18479108/b7b63158-79a1-11e6-81c2-14d8918bdb39.png)

**Comment by KingOfBrian** [comment]
@jdhealy pointed me to his [.travis.yml](https://github.com/jdhealy/PrettyColors/blob/development/.travis.yml) file which we should be able to steal the template from and add the existing simulator warm-up behavior

**Comment by ZevEisenberg** [comment]
The simulator warm-up doesn't work :(

**Comment by KingOfBrian** [comment]
CI is working!
