### ISSUE TITLE
Trim trailing NSKernAttributeName when extending

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#187]
The append API does not support removing the `NSKernAttributeName` currently. The BonMot "extend" API could remove the attribute from the attributes dictionary of the last character and add a `BONRemovedKernAttributeName` key with the original numeric value value of `NSKernAttributeName`. Then future calls to BonMot's "extend" API can swap the `BONRemovedKernAttributeName` value back to `NSKernAttributeName`.

This would still cause issues if the consumer used the stock `NSMutableAttributedString` "append" API, which is unfortunate.

**Comment by KingOfBrian** [comment]
We are not going to do this, and instead will push users towards the join API.
