### ISSUE TITLE
Review UIKit extensions

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#191]
- [x] `StyleableTextContainer`
- [x] Triggering adaptive updates on style set
- [x] Should `UITextView` and `UITextField` have different style objects for `typingAttributes` and `attributedPlaceHolder`?
- [x] Should we have 3 categories for usecases or 1 file for UIKit class extension?

**Comment by KingOfBrian** [comment]
Resolved by #210
