### ISSUE TITLE
swift 3.0 support for carthage

### ISSUE THREAD

**Issue by rahthakor** [Raizlabs/BonMot#195]
I just installed latest with Carthage but I'm not able to use it.

It gives me the error below.

```
*** Skipped building BonMot due to the error:
Dependency "BonMot" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Raizlabs/BonMot/issues/new
```

Please provide any relevant information how to use this library.
This lib is not generating .framework for following command
```
carthage update --platform iOS
```

**Comment by RoninSTi** [comment]
I came here to file a similar issue, using the same command.

**Comment by leoneparise** [comment]
I had the same problem but with Swift2.3. You can use my repo for that:
`github "leoneparise/BonMot" "master"`

I merged `BonMot` and `BonMot/UIKit` in only one framework. Have fun =)

**Comment by rahthakor** [comment]
@leoneparise I had installed  xCode 8.0 and it has installed swift 3.0 by default so I don't know how to compile with a different toolchain.

**Comment by leoneparise** [comment]
@rahthakor just put `github "leoneparise/BonMot" "master"` and you're done. `master` branch is configured to compile with Swift 3.0.

**Comment by rahthakor** [comment]
@leoneparise  Thank you man for a guidance

**Comment by ZevEisenberg** [comment]
@leoneparise thanks for lending a hand. We're also merging the UIKit subspec into the main project in the upcoming 4.0 release, so this problem shouldn't occur any more. You can see more at the work-in-progress 4.0 pull request here: #180. I'm going to close this issue, but please feel free to open another if you have any more questions 😄

**Comment by leoneparise** [comment]
@ZevEisenberg I use Carthage a lot. My account has lot's of libraries that I need to fix to integrate with Carthage. If you need any hand on Carthage build, let me know. =)

**Comment by ZevEisenberg** [comment]
@leoneparise thanks - we'll let you know if we run into issues closer to release time. In the meantime, if you're interested in the direction that BonMot is headed for 4.0, we just updated some early sample code in the description of https://github.com/Raizlabs/BonMot/pull/180.

**Comment by leoneparise** [comment]
@ZevEisenberg  I really liked the new API! I'm going to post my comments.
