### ISSUE TITLE
Target or script to build all permutations

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#203]
When working on BonMot, you need to build each of the four test targets (watchOS, tvOS, macOS, iOS) twice: Swift 2.3 and 3.0. It would be nice to have a target or script that can build all of those.

Also worth considering:
- is the example app part of this?
- what about Swift 2.2?

**Comment by KingOfBrian** [comment]
I added an 'AllTheThings' Target to build and test on 2.3 and 3.0 across all targets. I want to wait till we merge the projects before adding the example app

**Comment by ZevEisenberg** [comment]
This was fixed at some point during or right after the 4.0 release. There's an AllTheThings target that builds and tests iOS, tvOS, and macOS, and builds the iOS example project and watchOS.
