### ISSUE TITLE
More streamlined image tinting

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#21]
`-[UIImage rz_tintedImageWithColor:]` exists, but you have to use it first before inserting the image into the string. It should be done automatically if a string with an embedded image also has a `textColor` set (or maybe use a separate `imageColor` property).

**Comment by mattThousand** [comment]
seconded. should be a separate property to account for cases in which requirements dictate that text and image have different colors.

**Comment by ZevEisenberg** [comment]
A `BonText` that has an image can't also have a string (the properties intentionally clobber each other), so just using `textColor` shouldn't be a problem.

**Comment by ZevEisenberg** [comment]
In the upcoming 4.0 release, images set to "automatic" or "always template" will now be tinted if they are styled with a color.
