### ISSUE TITLE
Promote font features to first party attributes

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#212]
`AttributedStringStylePart` currently has a `fontFeature(FontFeatureProvider)` member, which means you have to know to use `fontFeature` if you want to control number case, number spacing, and other potentially supported font features in the future. This seems like an implementation detail. While `.fontFeature(FontFeatureProvider)` should remain present in order to support extensibility, first-party supported font features should be promoted to top-level members of `AttributedStringStylePart`. Proposal:

- `numberCase(NumberCase)` with members `.upper` and `.lower`
- `numberSpacing(NumberSpacing)` with members `.monospaced` and `.proportional`

These could keep their existing implementation - I just want to expose them in a more friendly way to the typical BonMot user.

**Comment by KingOfBrian** [comment]
Fixed by #213
