### ISSUE TITLE
Carthage Support fails if SwiftLint isn't upgraded

### ISSUE THREAD

**Issue by dostrander** [Raizlabs/BonMot#215]
If you aren't up to date with swiftlint it'll try to lint and fail. Might want to just put the binary right in the project and call it directly

**Comment by ZevEisenberg** [comment]
@dostrander would you mind posting the version of SwiftLint you were using that caused it to fail? I'm guessing that not just any outdated version would cause it.

**Comment by KingOfBrian** [comment]
Great point though @dostrander  -- Can we tell if we're building from inside carthage via the env? if so we could disable swiftlint on Carthage builds.

**Comment by dostrander** [comment]
@ZevEisenberg I upgraded after it failed and i'm not sure which one I was. But either way i would just do a `swiftlint || warn "Swiftlint isn't installed properly on this machine"`
or something, I think that'd be sufficient

**Comment by ZevEisenberg** [comment]
I'm not sure when we fixed this, but the behavior suggested by @dostrander is now how this works in the BonMot project.
