### ISSUE TITLE
Change StylePart to StringStyle.Part

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#232]
Instead of having `StylePart` as a top-level enum, nest it in an extension of `StringStyle`:

```swift
extension StringStyle {

    public enum Part {
        ...
    }

}
```

What do people think? Comment below!

**Comment by Imperiopolis** [comment]
Very much in favor of this.

**Comment by KingOfBrian** [comment]
Yea, +1!

**Comment by ZevEisenberg** [comment]
I'll take this.

**Comment by ZevEisenberg** [comment]
Closed by https://github.com/Raizlabs/BonMot/commit/65429d7b6b41ede68192001e09e0e0da42527eee
