### ISSUE TITLE
Can't build example app on device

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#240]
Anyone able to get this working? Would love to fix it, just because there's no reason it shouldn't work.

**Comment by ZevEisenberg** [comment]
If I set up all the signing stuff to get Xcode to stop complaining, I still get this:

```
dyld: Library not loaded: @rpath/BonMot.framework/BonMot
  Referenced from: /var/containers/Bundle/Application/C463249A-B89A-4B83-A7B6-0E0DA19F39FD/Example-iOS.app/Example-iOS
  Reason: image not found
```

**Comment by yujunkim** [comment]
Add BonMot.framework to Embedded Binaries in General

This work for me

**Comment by ZevEisenberg** [comment]
@yujunkim thanks for the tip! That worked for me. Check out #258.
