### ISSUE TITLE
Use mutable attributed strings instead of concatenation

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#25]
In Apple's WWDC 2012 talk that introduces attributed strings on iOS 6, they mention that modifying an attributed string is more efficient than concatenating multiple attributed strings. I would like to write some tests to confirm this, and if it is still true, change BonMot to use mutable attributed strings when building its strings.

**Comment by KingOfBrian** [comment]
Resolved in 4.0
