### ISSUE TITLE
InterfaceBuilder action connection issue

### ISSUE THREAD

**Issue by NikolaevSergey** [Raizlabs/BonMot#261]
Interface Builder doesn't show 'action' connection type when trying to create connection.
I was searching for information about it and have found [that](http://stackoverflow.com/questions/28732903/cant-connect-ibaction-in-xcode) (comment and last answer)
When I remove the pod action type is appeared again

Looks like that's occurs because the pod uses some extensions for UIButton.
As it appears that xCode bug but maybe you can do something with that? For example use custom button class or move this extension to separate pod?
Thanks!

**Comment by ZevEisenberg** [comment]
@NikolaevSergey thanks for taking the time to write in. This was resolved in BonMot 4.0.2 via #252 recently. Please update to that version and let us know if you're still having issues!

**Comment by NikolaevSergey** [comment]
@ZevEisenberg Sorry!
Yes, in new version works fine, thanks!
