### ISSUE TITLE
Remove NSKernAttributeName from last character

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#284]
If centered text has tracking applied (nonzero and non-nil `NSKernAttributeName`), the extra spacing is applied to the last character as well, which can make the text look not-centered. To fix this, when text is centered (or always?), we should remove this attribute from the last character. Thanks to @ndonald2 for teaching me about this.

This was supported in BonMot 3.x, so it's a regression that it doesn't work in 4.x.

**Comment by ZevEisenberg** [comment]
Example of the problem:
![screen shot 2017-05-04 at 11 16 00 am](https://cloud.githubusercontent.com/assets/464574/25710724/141a88f6-30bb-11e7-9f9a-5f5e3aa8920f.png)

**Comment by ZevEisenberg** [comment]
Now thinking it should always be removed, not just from centered text.

**Comment by ndonald2** [comment]
I believe it will factor into trailing constraints with other views, but I'm not 100% sure. In that case it should probably be removed from text of any alignment so that developers can configure constraints with the trailing edge of the last glyph rather than accounting for the extra space, as it would be for labels with default kerning.

**Comment by ZevEisenberg** [comment]
Agreed, and that's what the test I just pushed tests for. Now I just need to write support for this, unless someone else wants to 😉 

A problem is that you can compose already-existing attributed strings. If they have kerning on the last character, we should remove it, but what if they already have it removed (pre-moved)? Should we re-add it if it's just missing from the last character? Weirdness abounds. Considering only doing that if it's being constructed in the context of `NSAttributedString.composed(of: [...])`, in which case it would use thread-local storage to store the context that it's being created in a concatenation context. BonMot <4.0 did this via the `-attributedStringLastConcatenant:` method.
