### ISSUE TITLE
Handling ranges

### ISSUE THREAD

**Issue by ekimia** [Raizlabs/BonMot#299]
Curious what your thoughts are @ZevEisenberg on handling different styles in a string given I don't see a reference to a Range object in your code. Lets take this for example:

```
This part is red. This part is blue.
```

**Comment by ZevEisenberg** [comment]
@ekimia the recommended way to handle that in BonMot is to use XML (see the XML section of the ReadMe for more information). Do you have a use case that wouldn't be handled well by XML?

**Comment by ekimia** [comment]
Ah great!. When I get some time ill play with adding a + operator for NSAttributedString to accomplish the same
