### ISSUE TITLE
Im facing some issues with the syntax in Xcode 9 ,

### ISSUE THREAD

**Issue by harshit-mapmyindia** [Raizlabs/BonMot#304]

**Comment by harshit-mapmyindia** [comment]
<img width="180" alt="screen shot 2017-10-10 at 3 01 16 pm" src="https://user-images.githubusercontent.com/32668977/31379520-165bf346-adcc-11e7-93d1-1566418b85e7.png">
<img width="1031" alt="screen shot 2017-10-10 at 3 01 44 pm" src="https://user-images.githubusercontent.com/32668977/31379521-168c5522-adcc-11e7-918d-0f05d54c7720.png">
<img width="1022" alt="screen shot 2017-10-10 at 3 01 26 pm" src="https://user-images.githubusercontent.com/32668977/31379522-16b92d54-adcc-11e7-8c79-da75cf6291e7.png">

**Comment by harshit-mapmyindia** [comment]
any idea how to at that in PodFile im new to this?

**Comment by ZevEisenberg** [comment]
That looks right to me. Here’s an example you can copy and paste: https://github.com/ZevEisenberg/Padiddle/blob/master/Padiddle/Podfile

**Comment by ZevEisenberg** [comment]
Oops, sorry, my mistake. That branch was merged and deleted. Please use the master branch for now.

**Comment by ZevEisenberg** [comment]
@harshit-mapmyindia BonMot 5 has been released, with support for Xcode 9 and Swift 4. Please update, and file a bug if you find any problems. Thanks for using BonMot!
