### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by armandsLa** [Raizlabs/BonMot#305]
When you plan to update `BonMot` to support Swift 4?

**Comment by ZevEisenberg** [comment]
Soon! Just landing a couple of final bug fixes 😅

If you can’t wait, or you’d like to test out the update, check out the feature/xcode-9 branch.

**Comment by ZevEisenberg** [comment]
@armandsLa BonMot 5 has been released, with support for Xcode 9 and Swift 4. Please update, and file a bug if you find any problems. Thanks for using BonMot!
