### ISSUE TITLE
carthage build failing

### ISSUE THREAD

**Issue by nboyd-sportdx** [Raizlabs/BonMot#309]
xcode 9.1

*** Building scheme "BonMot-iOS" in BonMot.xcodeproj
Build Failed
	Task failed with exit code 65:

anyone experience this?  any solution?

**Comment by ZevEisenberg** [comment]
I know you emailed me some of this in private, but just for completeness and so other people can benefit, could you please provide a little more detail on how your project is set up? Precise repro steps or a sample project would be greatly appreciated if you have the time.

**Comment by nboyd-sportdx** [comment]
cartfile entry:
github "Raizlabs/BonMot"

carthage version:   0.26.2

error from terminal when trying to update:
*** Building scheme "BonMot-iOS" in BonMot.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Project\ Work/Source\ Code/...-iOS/Carthage/Checkouts/BonMot/BonMot.xcodeproj -scheme BonMot-iOS -configuration Release -derivedDataPath /Users/Nathan/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/BonMot/5.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath ./ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Project Work/Source Code/...-iOS/Carthage/Checkouts/BonMot)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/gv/qkc8m_v51lv_0cm6ygj0gcp00000gn/T/carthage-xcodebuild.FWn1RU.log

**Comment by nboyd-sportdx** [comment]
i was digging thought he log file that carthage makes and saw this line:

SwiftLint failed with exit code 2. Is SwiftLint installed and up to date?

do i downloaded and re-installed (i think i did it before) swift lint

i did two tests and had no problems so far.   now i dread converting my project to swift 4.   thank goodnees for source control

**Comment by ZevEisenberg** [comment]
Hm, interesting. We could probably make SwiftLint fail less hard in that case. It looks like Carthage defines a build setting for `CARTHAGE=YES` https://github.com/Carthage/Carthage/pull/1151/files. @nboyd-sportdx would you be interested in adding a pull request that does not fail SwiftLint when building via Carthage?
