### ISSUE TITLE
Fail to cast for Dictionary

### ISSUE THREAD

**Issue by mtfum** [Raizlabs/BonMot#312]
Hello. It's nice Open Source.

I want to use BonMot 5.0.
```swift
textView.typingAttributes = StringStyle().attributes
```
This code cause below error.
```
cannot assign value of type 'StyleAttributes'(aka 'Dictionary<NSAttributedStringKey, Any>') to type '[String:Any]'
```

How can I do that?

Do you have any Idea to resolve this?

thanks.

**Comment by mtfum** [comment]
I resolved by myself! Close this issue

**Comment by ZevEisenberg** [comment]
Glad to hear it! Any chance you could post your solution, in case someone else has the same problem?

**Comment by mtfum** [comment]
Sorry too late.
I could fix it with below extension!

```swift

extension StringStyle {

  func dictionary() -> [String:Any] {
    let _dictionary = attributes

    var dic = [String : Any].init(minimumCapacity: _dictionary.count)

    for a in _dictionary {
      dic[a.key.rawValue] = a.value
    }

    return dic
  }
}
```

**Comment by ZevEisenberg** [comment]
Ah, cool. I found a [nice, concise way to do this](https://gist.github.com/ZevEisenberg/66cd1f8aa25d34a3f22b85e933fa4ac8) as well:

```swift
extension Dictionary where Key == NSAttributedStringKey {

    var withStringKeys: [String: Value] {
        return reduce(into: [:], {
            $0[$1.key.rawValue] = $1.value
        })
    }

}
```

And then you use it like `textView.typingAttributes = StringStyle().attributes.withStringKeys`

**Comment by KingOfBrian** [comment]
Maybe `attributesDictionary` in addition to `attributes`? Seems like all the apis will move away from attributes eventually, but in the mean time it'd be nice to have a quick fix.

**Comment by ZevEisenberg** [comment]
Yes, we should put some kind of patch in for this. I don’t think `attributesDictionary` is right, because they’re both dictionaries. Maybe `stringKeyedAttributes`, or for better autocomplete, `attributesWithStringKeys`.
