### ISSUE TITLE
Trying to build my project gives me 56 compiler errors

### ISSUE THREAD

**Issue by SenorWesley** [Raizlabs/BonMot#317]
I updated my pods about 20 minutes ago, and after that, whenever I try to compile and build my project, I get a total of 56 compiler errors back from Xcode.

<img width="253" alt="schermafbeelding 2018-01-25 om 10 01 23" src="https://user-images.githubusercontent.com/15349051/35379553-c6c59f5a-01b6-11e8-9e6b-223bd0539911.png">

It this a problem anyone else experienced? Build settings:

<img width="805" alt="schermafbeelding 2018-01-25 om 10 03 37" src="https://user-images.githubusercontent.com/15349051/35379651-12dcf2da-01b7-11e8-9a0b-ae69efe16f81.png">

**Comment by ZevEisenberg** [comment]
@SenorWesley thanks for writing in. It looks like your project is building in Swift 3.2, but the latest BonMot only supports Swift 4. I should be able to add a `swift_version` flag to the podspec that will work as long as you're using CocoaPods 1.4. But until then, here's a fix that you can put at the bottom of you Podfile:

```ruby
# This is a hack to support both 3.2 and 4.0 pods. Add the pod name to the array below to build in 4.0.
#
# https://github.com/CocoaPods/CocoaPods/issues/7134 is the official thread tracking the issue.
SWIFT_4_PODS=['BonMot']

post_install do |installer|
  require 'fileutils'
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = SWIFT_4_PODS.include?(target.name) ? '4.0' : '3.2'
    end
  end
end
```

**Comment by Dimillian** [comment]
See: https://github.com/Raizlabs/BonMot/pull/310
