### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by ateliercw** [Raizlabs/BonMot#32]
I'd like to see carthage support alongside cocoa pods support so that I can use my dependency manager of choice

**Comment by ZevEisenberg** [comment]
Can't you just put `github "Raizlabs/BonMot"` in your Cartfile? Would anything in this repo need to change?

**Comment by ZevEisenberg** [comment]
I could add a section to the ReadMe.

**Comment by ateliercw** [comment]
You need an xCodeProj that build bonMot as a framework with a public target to support carthage

**Comment by ZevEisenberg** [comment]
This was closed when #65 was closed.
