### ISSUE TITLE
replace specific XML tags with UIImage. 

### ISSUE THREAD

**Issue by hakim89** [Raizlabs/BonMot#321]
I need to add bootstrap-like badges in my attributedString. For example I need to replicate this HTML in a UILabel in Swift using BonMot library:

<img width="293" alt="screen shot 2018-02-06 at 5 11 10 pm" src="https://user-images.githubusercontent.com/5322581/35886969-d2b00ba8-0b60-11e8-80da-f909549fd1f5.png">

I run some regex on my string to create a XML tag that looks like this `<badge>abbreviation</badge>` which i'm trying to make it look like the HTML. 

My first approach was to style that tag to look like a badge but couldn't make it look exactly like a badge.

Second approach is to replace it with an image. I have some code to make a UIImage from any string. For example: "abbreviation".toBadgeImage() will create an image that looks like this. 
<img width="77" alt="screen shot 2018-02-06 at 5 16 11 pm" src="https://user-images.githubusercontent.com/5322581/35887185-7c40667c-0b61-11e8-82ed-0a39ed340cd0.png"> 
Next step where i'm stuck is replacing that XML tag with the resulting UIImage.

would greatly appreciate any input on how to take this functionality to the finish line.

**Comment by ZevEisenberg** [comment]
Hey, @hakim89. You should be able to add an `enter` rule that will handle this for you. You can see an example in the demo project: https://github.com/Raizlabs/BonMot/blob/master/Example-iOS/DemoStrings.swift#L61. Please check that out, and let me know if you run into any problems.

**Comment by ZevEisenberg** [comment]
Good question! The image is being tinted because the default rendering mode for a UIImage is `automatic`. You should be able to set it to `alwaysOriginal` via `myImage.withRenderingMode(.alwaysOriginal)`, and BonMot will respect that and not tint the image.
