### ISSUE TITLE
issue when trying to build

### ISSUE THREAD

**Issue by Nathan187** [Raizlabs/BonMot#332]
is anyone else seeing this?  

*** DESERIALIZATION FAILURE (please include this section in any bug report) ***
could not deserialize type for 'StyleAttributes': declaration is not a nominal type
Cross-reference to module 'Foundation'

**Comment by ZevEisenberg** [comment]
@Nathan187 thanks for reporting this. Would you mind telling me what version of Xcode, BonMot, and Swift you're using?

**Comment by Nathan187** [comment]
no longer an issue.....did a clean build folder, deleted derive data...built libraries again...all well...sorry for the false alarm
