### ISSUE TITLE
Tests do not pass for iPhone 5S/SE sizes on iOS 11

### ISSUE THREAD

**Issue by chrisballinger** [Raizlabs/BonMot#336]
BonMot_iOSTests.AdaptiveStyleTests
testPreferredFontWithPreferredAdaptation, XCTAssertEqualWithAccuracy failed: ("26.0") is not equal to ("27.0") +/- ("0.001") - 
/Users/chrisbal/Documents/Beach/BonMot/Tests/AdaptiveStyleTests.swift:113
```
        BONAssert(attributes: testAttributes(UIContentSizeCategory.small), query: { $0.pointSize }, float: 26)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.medium), query: { $0.pointSize }, float: 27)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.large), query: { $0.pointSize }, float: 28)
  ```
testPreferredFontWithPreferredAdaptation, XCTAssertEqualWithAccuracy failed: ("26.0") is not equal to ("28.0") +/- ("0.001") - 
/Users/chrisbal/Documents/Beach/BonMot/Tests/AdaptiveStyleTests.swift:114
```
        BONAssert(attributes: testAttributes(UIContentSizeCategory.medium), query: { $0.pointSize }, float: 27)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.large), query: { $0.pointSize }, float: 28)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraLarge), query: { $0.pointSize }, float: 30)
  ```
testPreferredFontWithPreferredAdaptation, XCTAssertEqualWithAccuracy failed: ("27.0") is not equal to ("30.0") +/- ("0.001") - 
/Users/chrisbal/Documents/Beach/BonMot/Tests/AdaptiveStyleTests.swift:115
```
        BONAssert(attributes: testAttributes(UIContentSizeCategory.large), query: { $0.pointSize }, float: 28)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraLarge), query: { $0.pointSize }, float: 30)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraExtraLarge), query: { $0.pointSize }, float: 32)
  ```
testPreferredFontWithPreferredAdaptation, XCTAssertEqualWithAccuracy failed: ("28.0") is not equal to ("32.0") +/- ("0.001") - 
/Users/chrisbal/Documents/Beach/BonMot/Tests/AdaptiveStyleTests.swift:116
```
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraLarge), query: { $0.pointSize }, float: 30)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraExtraLarge), query: { $0.pointSize }, float: 32)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraExtraExtraLarge), query: { $0.pointSize }, float: 34)
  ```
testPreferredFontWithPreferredAdaptation, XCTAssertEqualWithAccuracy failed: ("30.0") is not equal to ("34.0") +/- ("0.001") - 
/Users/chrisbal/Documents/Beach/BonMot/Tests/AdaptiveStyleTests.swift:117
```
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraExtraLarge), query: { $0.pointSize }, float: 32)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraExtraExtraLarge), query: { $0.pointSize }, float: 34)
    }
  ```
testTextStyleAdapt, XCTAssertEqualWithAccuracy failed: ("26.0") is not equal to ("27.0") +/- ("0.001") - 
/Users/chrisbal/Documents/Beach/BonMot/Tests/AdaptiveStyleTests.swift:96
```
        BONAssert(attributes: testAttributes(UIContentSizeCategory.small), query: { $0.pointSize }, float: 26)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.medium), query: { $0.pointSize }, float: 27)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.large), query: { $0.pointSize }, float: 28)
  ```
testTextStyleAdapt, XCTAssertEqualWithAccuracy failed: ("26.0") is not equal to ("28.0") +/- ("0.001") - 
/Users/chrisbal/Documents/Beach/BonMot/Tests/AdaptiveStyleTests.swift:97
```
        BONAssert(attributes: testAttributes(UIContentSizeCategory.medium), query: { $0.pointSize }, float: 27)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.large), query: { $0.pointSize }, float: 28)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraLarge), query: { $0.pointSize }, float: 30)
  ```
testTextStyleAdapt, XCTAssertEqualWithAccuracy failed: ("27.0") is not equal to ("30.0") +/- ("0.001") - 
/Users/chrisbal/Documents/Beach/BonMot/Tests/AdaptiveStyleTests.swift:98
```
        BONAssert(attributes: testAttributes(UIContentSizeCategory.large), query: { $0.pointSize }, float: 28)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraLarge), query: { $0.pointSize }, float: 30)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraExtraLarge), query: { $0.pointSize }, float: 32)
  ```
testTextStyleAdapt, XCTAssertEqualWithAccuracy failed: ("28.0") is not equal to ("32.0") +/- ("0.001") - 
/Users/chrisbal/Documents/Beach/BonMot/Tests/AdaptiveStyleTests.swift:99
```
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraLarge), query: { $0.pointSize }, float: 30)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraExtraLarge), query: { $0.pointSize }, float: 32)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraExtraExtraLarge), query: { $0.pointSize }, float: 34)
  ```
testTextStyleAdapt, XCTAssertEqualWithAccuracy failed: ("30.0") is not equal to ("34.0") +/- ("0.001") - 
/Users/chrisbal/Documents/Beach/BonMot/Tests/AdaptiveStyleTests.swift:100
```
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraExtraLarge), query: { $0.pointSize }, float: 32)
        BONAssert(attributes: testAttributes(UIContentSizeCategory.extraExtraExtraLarge), query: { $0.pointSize }, float: 34)
    }
  ```
     Executed 110 tests, with 10 failures (0 unexpected) in 0.623 (0.725) seconds

**Comment by chrisballinger** [comment]
From further investigation, it appears that this only affects iOS 11.3 and not iOS 10.3.1.

**Comment by ZevEisenberg** [comment]
We might be able to fix this by using a different (or custom) font that didn't change between iOS versions. We can use EBGaramond, which is embedded in the tests. You just have to use the EBGaramondLoader before trying to use the font.
