### ISSUE TITLE
Argument passed to call that takes no arguments

### ISSUE THREAD

**Issue by ServusJon** [Raizlabs/BonMot#348]
Any hints?

<img width="754" alt="bildschirmfoto 2018-10-07 um 21 17 28" src="https://user-images.githubusercontent.com/783416/46585847-85877980-ca76-11e8-85c5-8d132cfa0861.png">

**Comment by ZevEisenberg** [comment]
@ServusJon would you mind posting which versions of Xcode, Swift, and BonMot you're using?

**Comment by danramirez** [comment]
Same error with last Xcode 10, Swift 4.2 and BonMont 5.3 version

**Comment by ZevEisenberg** [comment]
I was not able to reproduce this in Xcode 10, Swift 4.2, iOS 12. The following code compiles fine:

```swift
let style = StringStyle(
    .font(UIFont(name: "Rubik-Medium", size: 16)!),
    .lineHeightMultiple(1.3)
)

let attributedString = "someString".styled(with: style)
UILabel().attributedText = attributedString
```

@ServusJon were you able to get this working? I'm wondering whether cleaning the project or deleting derived data might help. The code looks fine, which makes me suspect it could be an Xcode problem.

**Comment by jaimeagudo** [comment]
I get the same _Argument passed to call that takes no arguments_ trying to rescue an old project, I upgraded to `5.3` 

```
  class func p2pGreen() -> UIColor    {
        //A6E22E
        return UIColor(red:0.65, green:0.89, blue:0.18, alpha:1.0)
    }
 
static let greenText = StringStyle(.color(.p2pGreen()))
```

I also get another unrelated error: _Value of type 'String' has no member 'styled'_

```
  return NSAttributedString.composed(of: [
            String(num).styled(with: .color(.white)),// greenText),
            " ",
            fbLabel.attributedText!.styled(with: iconStyle),
            (small ? "" : " friends".styled(with: .color(.white)))]
        )

```


Using Xcode Version 10.0 (10A255), Swift 3

I made sure the Pods->Target-> BonMot -> Swift Language Version is 4.2

Any help highly appreciated

**Comment by s2imon** [comment]
I've updated my project from an older version to latest version (Installing BonMot 5.3 (was 4.3.1)). And I'm getting the same errors that I can't get rid of. Any ideas?

Xcode 10.1, Swift 3, BonMOt 5.3

https://cl.ly/26c6e0c82ad7
https://cl.ly/a9f8388ac911
https://cl.ly/6b994efbc939
https://cl.ly/5b39c254a290

I'm not sure where to get started. Thanks @ZevEisenberg ! Or did any of you in this thread got it figured out in the meantime @ServusJon @jaimeagudo? 🙌

**Comment by ZevEisenberg** [comment]
BonMot no longer supports Swift 3. Please try updating to Swift 4. (Apple is dropping Swift 3 in the next version of Xcode, so this is probably a good idea in general.) I tried supporting both Swift 3 and 4 in BonMot, but due to changes in `NSAttributedString.Key`, I wasn't able to make it work without duplicating the bulk of the code in the library, and given Apple's aggressive deprecation cycle, I decided it wasn't worth it at the time.

**Comment by s2imon** [comment]
I'm doing that now, just a few things left to convert and will try again and report back. Thanks @ZevEisenberg.

**Comment by s2imon** [comment]
@ZevEisenberg I apologise, that indeed seems to fix the issue for me! Thank you so much.
