### ISSUE TITLE
Make it easy to query a font's features

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#35]
Provide a convenience wrapper around `CTFontCopyFeatures()` so users can easily see if a font supports a requested feature. Could possibly have it take a parameter, and do the heavy lifting behind the scenes:

```objc
typedef NS_ENUM(NSUInteger, BONFontFeature) {
    BONFontFeatureUnknown = 0,
    BONFontFeatureSmallCaps,
    BONFontFeatureMonospaceFigures,
    ...
}

+ (BOOL)font:(UIFont *)font supportsFeature:(BONFontFeature)feature;
```

**Comment by ZevEisenberg** [comment]
Or possibly make it an instance method on `BONText`/`BONChain`: `- (BOOL)supportsFeature:(BONFontFeature)feature`. It would throw a runtime exception (or return `NO`) if the font is not set.

**Comment by KingOfBrian** [comment]
Dup #173
