### ISSUE TITLE
Better printing of special characters

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#42]
- [x] Make a function that will pretty-print any string's special characters
- [ ] Option to print inline or one-character-per-line
- [ ] Option to include image addresses or not (for determinism)
- [ ] Make `-debugDescription` on `BONText` and `BONChain` use these methods.
- [ ] Unit tests
- [ ] Optional: add category to `NSString` to make this more streamlined.

**Comment by ZevEisenberg** [comment]
This is partially addressed in https://github.com/Raizlabs/BonMot/pull/125

**Comment by KingOfBrian** [comment]
Resolved in 4.0
