### ISSUE TITLE
Add syntax complex chain composition

### ISSUE THREAD

**Issue by ateliercw** [Raizlabs/BonMot#66]
I'd like to use logical operations while composing a chain, for instance conditionally appending an icon to a string based on validity of a form.

I created a very basic linkWithChain method and wrote some tests, https://github.com/Raizlabs/BonMot/tree/feature/ateliercw/linkable_chains it serves my purposes, but I haven't tested it's ability to compose attributed strings across chains well and requires a less naive implementation of the linkWithChain: methods.

**Comment by ZevEisenberg** [comment]
@ateliercw thanks for your input! I’ve incorporated your ideas into #72.
