### ISSUE TITLE
Center the text?

### ISSUE THREAD

**Issue by sabernar** [Raizlabs/BonMot#67]
Am I missing something or is there no way to center or right justify the attributed string?

**Comment by ZevEisenberg** [comment]
It's something I intend to add. I built BonMot mostly to cover cases I had encountered in my last app, and thus far I hadn't needed to do that kind of text alignment. Issue #10 touches on this. Is it something you'd like to use in a project? If so, would you be interested in submitting a pull request? I can help with the DSL stuff, which can be tricky, if you're interested.

**Comment by sabernar** [comment]
I added simple text alignment, but I only need it for BONText, so it seems like it was pretty straightforward.  So far I am only using BonMot for relatively straightforward use cases, so my text alignment works fine, but I'm guessing there is a lot more that needs to be done in order for it to work throughout the app.

**Comment by ZevEisenberg** [comment]
It's not too involved to add support to `BONChain`. Just need to add block typedefs, properties, and make sure that `-copy` works correctly. Oh, and tests :)

**Comment by ZevEisenberg** [comment]
Closed via #79. @sabernar let me know if this works for you!
