### ISSUE TITLE
Support styling localized strings

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#69]
Richly formatted localized strings are a problem, because you can't just search for a substring and apply a different style. Homonyms, duplicated or missing words, and word order all affect this. The best solution will probably involve some form of markup/markdown/HTML/CSS. I'm very open to suggestions for how to do this. My first inclination is to have code to assign `BONText` objects to Markdown formatting specifiers, but it may provide enough granular control. Might need more of a CSS-style class/inheritance system, but by that point we're getting dangerously close to just using `[NSAttributedString initWithData:options:documentAttributes:error:]`.

**Comment by graiz** [comment]
I think CSS is particularly problematic and you may prefer a declarative way to define mid-string styles. I much prefer the approach used by PrintF that uses the mid string $1, $2 and then defines the inputs. This allows for localization while allowing sentence and verb structure to be altered.
  "$1 is a foo, who ran $2" , sub in "Greg" and "2 Miles"
 In another language the sentence structure could be:
   "A foo is $1, ran $2 he did."
If formatting is applied to the substitutions you'll have pretty good international support without having to parse and process CSS.

**Comment by ZevEisenberg** [comment]
This can get hairy with languages that have, for example, different systems of pluralization or gender. @lsavino did a great talk on this at AltConf: https://realm.io/news/altconf-laura-savino-localization-because-n-est-pas-por-todo-el-mundo/

**Comment by smbarne** [comment]
@ZevEisenberg I would also +1 with `vararg` approach from @graiz to start with at least.  With one modification - that the whole thing could also be powered by a format string.

> "$1 is a foo, who ran $2" , sub in "Greg" and "2 Miles"

could be a powered by a format string

> "%@ is a foo, who ran %@"

That was the format string is localizable, and the ordering of dynamic properties could be adjusted on a language by language basis per string.

**Comment by ZevEisenberg** [comment]
@smbarne but if you use `%@` instead of `%1$@`, then word order becomes an issue. The reason that I like inline formatting tags, like HTML or Markdown, is that then the person who does localization can just control the whole thing, without needing to deal with things like a variable number of positional parameters, some of which may not exist in all languages. This would also make it easy to write an API that just returns a localized string with inline style markers, ready for consumption by BonMot. Drawback: not very portable to systems that don't use BonMot (read: cross platform), because you have to write a parser.
