### ISSUE TITLE
Add newlines to BONSpecial

### ISSUE THREAD

**Issue by ateliercw** [Raizlabs/BonMot#70]
Having a nicely named line break in bon special would cut down on needing to specify one in the central strings for a project

**Comment by ZevEisenberg** [comment]
Do you mean `\n`? What's the `CFStringTransform` name for that character? Will `BONSpecialGenerator.swift` handle it? I typically just use `\n` inline for clarity, but it could be useful to have.

Are there any other line break characters we might want to add?

**Comment by ateliercw** [comment]
Looking at it, the newline's CFStringTransform value is garbage (`<control000A>`), so it won't integrate nicely into BONSpecial unless it were added differently from the rest of the array.

Paragraph separator is probably worth adding, it comes in as:
```
+ (NSString *)paragraphSeparator { return @"\u2029"; }
```
Testing those I also found some changes that needed to happen for the Xcode-7 gm, so I'm PRing those

**Comment by ZevEisenberg** [comment]
relevant: https://openradar.appspot.com/radar?id=6665236568342528

**Comment by ZevEisenberg** [comment]
This was addressed in #71.
