### ISSUE TITLE
copyWithoutNextText and changing font,color

### ISSUE THREAD

**Issue by badeleux** [Raizlabs/BonMot#87]
I created a chain of strings (by appending). I was totally sure that when I set font and color on chained string it will color and change font on all links. But it's not, BONChain discards all links and change font and color only on root.

Why is that?

**Comment by ZevEisenberg** [comment]
@badeleux the idea is to use `BONChain` to build up a string from pieces. It wasn’t designed to allow global operations to modify a chain once it has been assembled. I would typically suggest doing what you’re asking like this:

```objc
BONChain *base = BONChain.new.textColor([UIColor redColor]);

BONChain *links = BONChain.new;
[links appendLink:base.string(@"first")];
[links appendLink:base.string(@"second") separator:@" "];

NSAttributedString *string = links.attributedString;
```

Would this server your needs? If not, could you provide a little more information or sample code on what you’re trying to do? I could see adding some kind of system of comparability for `BONChain` or `BONText`, but I’d like to know how it’s being used first.

**Comment by badeleux** [comment]
Let's imagine example where we have 

```
let str = <String><Image><String>
```

 I don't wanna set properties on each string, I wanna do it globally when the string is already assembled. 
I think nobody expects that textColor may not work, and certainly that this method destroys built string.

**Comment by ZevEisenberg** [comment]
Would you mind posting specific code for what you're doing, with an expected outcome and an actual outcome? Or even better, a failing unit test in a PR? I just want to make sure I understand exactly what pieces of syntax you're using.

By the way, thanks for your interest in BonMot! I see that you're doing a lot with functional programming. I'm starting to learn FP, and I hope that what I learn will find its way into BonMot at some point.

**Comment by KingOfBrian** [comment]
We're closing this issue as it shouldn't be a problem with the upcoming Swift based 4.0 API. Check out #180 if you're interested in taking a look!
