### ISSUE TITLE
Optimize for use with RZDataBinding

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#9]
@jvisenti are there things we can do to make BonMot play nice with [RZDataBinding](https://github.com/Raizlabs/RZDataBinding)? If an attributed string is updated each time one of several properties changes, can we make string re-generation faster by caching or coalescing things?

**Comment by jvisenti** [comment]
Closest thing I can think of offhand is https://github.com/jvisenti/RZConfiguration/blob/develop/RZConfiguration/RZTextConfiguration.m. Notice that although the attributedString is invalidated with each change (thereby emitting a KVO change), it is not actually computed until next time it is accessed (or, I suppose, if someone is KVOing it with `NSKeyValueObservationOptionOld`. 

Even as it is, it seems like `RZManuscript` could be very binding-friendy. What I'm still trying to figure out is how bindings can work with use of `RZChainLink`, which recreates manuscripts via copying each time.

**Comment by KingOfBrian** [comment]
Not implementing tight coupling between these libraries
